Repository dfr99/SwimChrono, pull requests merged in 2024-04, with the labels that each got.

#62 Definición de fragments
  docs/components/index.md
  docs/images/components/fragments.png
  mkdocs.yml
Labels: documentation

#64 Bug/AndroidManifest.xml
  app/SwimChrono/app/src/main/AndroidManifest.xml
  app/SwimChrono/app/src/main/res/drawable/flecha_salida_pressed_v2.xml
  app/SwimChrono/app/src/main/res/drawable/flecha_salida_unpressed_v2.xml
  app/SwimChrono/app/src/main/res/drawable/flecha_salida_v2.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_info.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_my_qractivity.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_notifications.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_settings.xml
  docs/development/wireframes-implementation.md
  docs/images/wireframes-implementation/fragment_profile_V1.png
  docs/images/wireframes-implementation/fragment_profile_V2.png
  docs/images/wireframes-implementation/profile_my_qr_V1.png
  docs/images/wireframes-implementation/profile_my_qr_V2.png
  docs/images/wireframes-implementation/profile_notifications_V2.png
  docs/images/wireframes-implementation/profile_personalinfo_V1.png
  docs/images/wireframes-implementation/profile_personalinfo_V2.png
  docs/images/wireframes-implementation/profile_settings_V2.png
Labels: bug, documentation

#67 Añadir la definición del servicio en la Wiki
  docs/components/index.md
Labels: documentation

#63 My Club landscape wireframes
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/club/RecyclerClubMembersListAdapter.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/club/RecyclerItemTrainerAdapter.kt
  app/SwimChrono/app/src/main/res/drawable/baseline_account_circle_24.xml
  app/SwimChrono/app/src/main/res/layout-land/fragment_club.xml
  app/SwimChrono/app/src/main/res/layout/fragment_club.xml
  app/SwimChrono/app/src/main/res/layout/item_user_card.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
  docs/development/wireframes.md
  docs/images/wireframes/Club landscape.png
Labels: feature

#71 app/GH-68 #68 layouts horizontales PROFILE + Actualizacion wiki
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileMyQRActivity.kt
  app/SwimChrono/app/src/main/res/layout-land/activity_profile_info.xml
  app/SwimChrono/app/src/main/res/layout-land/activity_profile_myqractivity.xml
  app/SwimChrono/app/src/main/res/layout-land/activity_profile_notifications.xml
  app/SwimChrono/app/src/main/res/layout-land/activity_profile_settings.xml
  app/SwimChrono/app/src/main/res/layout-land/fragment_profile.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_myqractivity.xml
  docs/components/index.md
  docs/development/wireframes.md
  docs/images/wireframes/Profile-landscape.png
Labels: documentation, app

#85 Add wireframes for landscape layouts
  docs/development/wireframes.md
  docs/images/wireframes/Club landscape.png
  docs/images/wireframes/races.png
  docs/images/wireframes/timer.png
  mkdocs.yml
Labels: documentation

#84 Refeere layout
  app/SwimChrono/app/src/main/AndroidManifest.xml
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/model/Race.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/cronometer/CronometerFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/RecyclerRacesListAdapter.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/RefereeFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/RefereeViewModel.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/TimerActivity.kt
  app/SwimChrono/app/src/main/res/drawable/icon_referee.xml
  app/SwimChrono/app/src/main/res/layout/fragment_cronometer.xml
  app/SwimChrono/app/src/main/res/layout/fragment_cronometer_start.xml
  app/SwimChrono/app/src/main/res/layout/fragment_referee.xml
  app/SwimChrono/app/src/main/res/layout/fragment_referee_start.xml
  app/SwimChrono/app/src/main/res/layout/item_race_info.xml
  app/SwimChrono/app/src/main/res/menu/bottom_nav_menu.xml
  app/SwimChrono/app/src/main/res/navigation/mobile_navigation.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
  docs/images/wireframes/Referee.png
Labels: feature
