Repository dfr99/SwimChrono, pull requests merged in 2024-03, with the labels that each got.

#23 Documentación sobre la integración con dispositivos Bluetooth
  docs/integrations/bluetooth.md
  mkdocs.yml
Labels: documentation

#32 Add custom theme to the app
  .gitignore
  app/SwimChrono/.idea/deploymentTargetDropDown.xml
  app/SwimChrono/.idea/gradle.xml
  app/SwimChrono/.idea/render.experimental.xml
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/MainActivity.kt
  app/SwimChrono/app/src/main/res/drawable-v24/selector_bottom_nav_item.xml
  app/SwimChrono/app/src/main/res/font-v26/font_family.xml
  app/SwimChrono/app/src/main/res/font-v26/montserrat_bold.ttf
  app/SwimChrono/app/src/main/res/font-v26/montserrat_regular.ttf
  app/SwimChrono/app/src/main/res/layout/activity_main.xml
  app/SwimChrono/app/src/main/res/layout/fragment_dashboard.xml
  app/SwimChrono/app/src/main/res/layout/fragment_home.xml
  app/SwimChrono/app/src/main/res/layout/fragment_notifications.xml
  app/SwimChrono/app/src/main/res/values-night/themes.xml
  app/SwimChrono/app/src/main/res/values/colors.xml
  app/SwimChrono/app/src/main/res/values/styles.xml
  app/SwimChrono/app/src/main/res/values/themes.xml
Labels: feature

#33 Nuevo botón creado + bug
  app/SwimChrono/.idea/gradle.xml
  app/SwimChrono/.idea/misc.xml
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/MainActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/club/ClubFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/club/ClubViewModel.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileViewModel.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/tournaments/TournamentsFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/tournaments/TournamentsViewModel.kt
  app/SwimChrono/app/src/main/res/drawable-v24/selector_bottom_nav_item.xml
  app/SwimChrono/app/src/main/res/drawable/icon_club.xml
  app/SwimChrono/app/src/main/res/drawable/icon_dashboard.xml
  app/SwimChrono/app/src/main/res/drawable/icon_profile.xml
  app/SwimChrono/app/src/main/res/drawable/icon_tournaments.xml
  app/SwimChrono/app/src/main/res/layout/activity_main.xml
  app/SwimChrono/app/src/main/res/layout/fragment_club.xml
  app/SwimChrono/app/src/main/res/layout/fragment_profile.xml
  app/SwimChrono/app/src/main/res/layout/fragment_tournaments.xml
  app/SwimChrono/app/src/main/res/menu/bottom_nav_menu.xml
  app/SwimChrono/app/src/main/res/navigation/mobile_navigation.xml
  app/SwimChrono/app/src/main/res/values-night/themes.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
  app/SwimChrono/app/src/main/res/values/styles.xml
  app/SwimChrono/app/src/main/res/values/themes.xml
Labels: bug, app

#34 3 layouts creados #28
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileViewModel.kt
  app/SwimChrono/app/src/main/res/drawable/celdas_profile_info.xml
  app/SwimChrono/app/src/main/res/drawable/ejemplo_qr.png
  app/SwimChrono/app/src/main/res/drawable/icon_notifications.xml
  app/SwimChrono/app/src/main/res/drawable/icon_personal_info.xml
  app/SwimChrono/app/src/main/res/drawable/icon_qr.xml
  app/SwimChrono/app/src/main/res/drawable/icon_settings.xml
  app/SwimChrono/app/src/main/res/layout/fragment_profile.xml
  app/SwimChrono/app/src/main/res/layout/profile_my_qr.xml
  app/SwimChrono/app/src/main/res/layout/profile_personalinfo.xml
  images/ejemplo_QR.png
Labels: feature

#35 Add Club Fragment
  app/SwimChrono/.idea/gradle.xml
  app/SwimChrono/.idea/migrations.xml
  app/SwimChrono/.idea/misc.xml
  app/SwimChrono/app/src/main/res/drawable/old_cf.png
  app/SwimChrono/app/src/main/res/layout/fragment_club.xml
  app/SwimChrono/app/src/main/res/layout/item_club_card.xml
  app/SwimChrono/app/src/main/res/layout/item_user_card.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
  app/SwimChrono/app/src/main/res/values/styles.xml
Labels: feature

#47 Add a custom logger
  app/SwimChrono/.idea/misc.xml
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/util/Logger.kt
Labels: feature

#49 Creación del comportamiento del DASHBOARD
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/dashboard/DashboardFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/dashboard/RecyclerTournamentAdapter.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/tournaments/TournamentInfoFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/tournaments/TournamentInfoViewModel.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/tournaments/TournamentsFragment.kt
  app/SwimChrono/app/src/main/res/layout/activity_main.xml
  app/SwimChrono/app/src/main/res/layout/fragment_tournament_info.xml
  app/SwimChrono/app/src/main/res/layout/item_race_card.xml
  app/SwimChrono/app/src/main/res/layout/item_tournament_card.xml
  app/SwimChrono/app/src/main/res/navigation/mobile_navigation.xml
  app/SwimChrono/app/src/main/res/values-night/themes.xml
  app/SwimChrono/app/src/main/res/values/styles.xml
Labels: feature

#50 Rama Feature/GH-XX sobre layouts de profile_fragment y más
  app/SwimChrono/.idea/gradle.xml
  app/SwimChrono/.idea/misc.xml
  app/SwimChrono/app/src/main/AndroidManifest.xml
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileFragment.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileInfoActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileMyQRActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileNotificationsActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileSettingsActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileViewModel.kt
  app/SwimChrono/app/src/main/res/drawable/button_settings.xml
  app/SwimChrono/app/src/main/res/drawable/celdas_profile_info.xml
  app/SwimChrono/app/src/main/res/drawable/flecha_salida.xml
  app/SwimChrono/app/src/main/res/drawable/flecha_salida_pressed.xml
  app/SwimChrono/app/src/main/res/drawable/flecha_salida_unpressed.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_info.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_my_qractivity.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_notifications.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_settings.xml
  app/SwimChrono/app/src/main/res/layout/fragment_profile.xml
  app/SwimChrono/app/src/main/res/layout/profile_my_qr.xml
  app/SwimChrono/app/src/main/res/layout/profile_personalinfo.xml
  app/SwimChrono/app/src/main/res/values/colors.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
Labels: feature

#51 docs/wireframes-implementation.md
  app/SwimChrono/app/src/main/res/layout/activity_profile_info.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_my_qractivity.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_notifications.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_settings.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
  docs/development/wireframes-implementation.md
  docs/images/wireframes-implementation/fragment_profile.png
  docs/images/wireframes-implementation/profile_my_qr.png
  docs/images/wireframes-implementation/profile_notifications.png
  docs/images/wireframes-implementation/profile_personalinfo.png
  docs/images/wireframes-implementation/profile_settings.png
Labels: documentation

#54 Feat: Creado Fragment cronometrador oficial
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/cronometer/CronometerFragment.kt
  app/SwimChrono/app/src/main/res/values/strings.xml
Labels: feature

#55 Remove .idea
  .gitignore
  .idea/.gitignore
  .idea/SwimChrono.iml
  .idea/modules.xml
  .idea/vcs.xml
Labels: bug

#56 Estrucutra inicial para la API
  .gitignore
  README.md
  app/SwimChrono/.gitignore
  app/SwimChrono/.idea/.gitignore
  app/SwimChrono/.idea/compiler.xml
  app/SwimChrono/.idea/deploymentTargetDropDown.xml
  app/SwimChrono/.idea/gradle.xml
  app/SwimChrono/.idea/kotlinc.xml
  app/SwimChrono/.idea/migrations.xml
  app/SwimChrono/.idea/misc.xml
  app/SwimChrono/.idea/render.experimental.xml
  app/SwimChrono/.idea/vcs.xml
  app/api/README.md
  app/api/commands/__init__.py
  app/api/pyproject.toml
  app/api/src/main.py
  app/api/src/requirements.txt
  app/api/src/swimchrono.db
  render.yaml
  requirements.txt
  swimchrono.db
Labels: feature
