Repository dfr99/SwimChrono, pull requests merged in 2024-05, with the labels that each got.

#100 Documentación del análisis de UX/UI
  .gitignore
  docs/favicon.png
  docs/ux/images/disposiciones/horizontal_1.png
  docs/ux/images/disposiciones/vertical_1.png
  docs/ux/images/disposiciones/vertical_2.png
  docs/ux/images/heat_map.jpeg
  docs/ux/images/login.png
  docs/ux/index.md
  mkdocs.yml
Labels: documentation

#99 App/GH-95
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/TimerActivity.kt
  app/SwimChrono/app/src/main/res/drawable/button_crono.xml
  app/SwimChrono/app/src/main/res/drawable/icon_play.xml
  app/SwimChrono/app/src/main/res/drawable/icon_repeat.xml
  app/SwimChrono/app/src/main/res/layout/fragment_referee_start.xml
  app/SwimChrono/app/src/main/res/values/colors.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
  docs/images/wireframes-implementation/wireframe-referee-chrono.jpg
  docs/images/wireframes-implementation/wireframe-referee-race-info.jpg
  mkdocs.yml
Labels: documentation, app

#105 Refactor on documentation
  docs/contributing/index.md
  docs/images/contributing/tbd.png
  docs/mkdocs.md
  docs/user-guide/getting-started.md
  docs/user-guide/tools.md
  mkdocs.yml
Labels: documentation

#110 App/GH-103: Información, layout de crono y notificaciones
  app/SwimChrono/app/src/main/AndroidManifest.xml
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/notifications/AlarmNotification.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/notifications/AlarmNotificationManager.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/notifications/BootReceiver.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileInfoActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileMyQRActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/TimerActivity.kt
  app/SwimChrono/app/src/main/res/drawable/button_crono.xml
  app/SwimChrono/app/src/main/res/drawable/icon_pause.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_info.xml
  app/SwimChrono/app/src/main/res/layout/fragment_referee_start.xml
Labels: app

#116 Edicion strings.xml completado
  app/SwimChrono/app/src/main/res/layout-land/activity_profile_info.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_info.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
Labels: duplicate, epic

#120 Review documentation and update wireframes implementation
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/club/ClubDataAdapter.kt
  docs/development/wireframes-implementation.md
  docs/images/wireframes-implementation/profile_login-land.png
  docs/images/wireframes-implementation/profile_login.png
  docs/images/wireframes-implementation/profile_my_qr_V2-land.png
  docs/images/wireframes-implementation/profile_my_qr_V2.png
  docs/images/wireframes-implementation/profile_personalinfo_V2-land.png
  docs/images/wireframes-implementation/profile_personalinfo_V2.png
  docs/images/wireframes-implementation/wireframe-referee-chrono-land.jpg
  docs/images/wireframes-implementation/wireframe-referee-chrono-vertical.jpg
  docs/integrations/bluetooth.md
  docs/integrations/firebase.md
  docs/integrations/zxing-qr.md
  images/ejemplo_QR.png
Labels: bug

#119 Add radiobutton to change Language
  app/SwimChrono/app/src/main/AndroidManifest.xml
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/BaseActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/MainActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileInfoActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileMyQRActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/profile/ProfileSettingsActivity.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/util/LocaleUtil.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/util/Storage.kt
  app/SwimChrono/app/src/main/res/layout-land/activity_profile_settings.xml
  app/SwimChrono/app/src/main/res/layout/activity_profile_settings.xml
  app/SwimChrono/app/src/main/res/values-es/strings.xml
  app/SwimChrono/app/src/main/res/values/strings.xml
  docs/ux/index.md
Labels: documentation, feature

#121 documentation/GH-117: Documentación de notificaciones y limpieza de comentarios
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/notifications/AlarmNotificationManager.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/notifications/BootReceiver.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/RefereeViewModel.kt
  app/SwimChrono/app/src/main/java/es/udc/apm/swimchrono/ui/referee/TimerActivity.kt
  docs/images/notifications/NotificacionEmergente.jpg
  docs/images/notifications/TablonTextoExpandido.jpg
  docs/integrations/notifications.md
Labels: documentation, final_revision
